name: array-api-intelligent-tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
permissions:
  actions: read
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ivy 🛎
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Update Mapping and Determine Tests
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        run: |
          source ./ivy/clone_mapping.sh master
          pip install pydriller pymongo 
          cp Mapping/tests.pbz2 ivy/
          cd ivy
          python run_tests_CLI/array_api_determine_tests.py
          cd ..
          cp ivy/tests.pbz2 Mapping/
          cd Mapping
          git add .
          git commit -m "Update Mapping"
          git push origin master
        continue-on-error: true

      - name: Run Tests
        id: tests
        run: |
          cd ivy
          python run_tests_CLI/array_api_run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} ${{ github.run_id }} ${{ steps.jobs.outputs.html_url }}
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
