name: array-api-intelligent-tests-pr
on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, review_requested ]

permissions:
  actions: read
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ivy 🛎
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Determine Tests
        run: |
          git clone -b master https://github.com/unifyai/Mapping.git --depth 1
          pip install pydriller
          cp Mapping/tests.pbz2 ivy/
          cd ivy
          python run_tests_CLI/array_api_determine_tests.py
        continue-on-error: true

      - name: Run Tests
        id: tests
        run: |
          cd ivy
          python run_tests_CLI/array_api_run_tests_pr.py
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
