name: test-ivy-cron
on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'
permissions:
  actions: read
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Run Tests
        id: tests
        run: |
          cd ivy
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          pip3 install pymongo
          python run_tests_CLI/cron_tests.py ${{ github.run_number }}
          python run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} 'false' 'false' ${{ github.run_id }} ${{ steps.jobs.outputs.html_url }}
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
